Specifying that Python is exclusively one-liners
exterkamp/exterkamp pull request #1
Opened 2020-07-21 23:23 UTC by zdiemer

It's important to specify here that your Python work is all one-liners.

2020-07-21 23:24 UTC, exterkamp requested changes

2020-07-21 23:24 UTC, exterkamp commented on README.md
> +These days I write mostly Go, Javascript, and C++; with some Python one-liners & Java in the past.
Surely this shouldn't be "some" if it's for one-liners?

```suggestion
These days I write mostly Go, Javascript, and C++; with many Python one-liners & Java in the past.
```

2020-07-21 23:31 UTC, exterkamp requested changes

2020-07-21 23:31 UTC, exterkamp commented on README.md
> +These days I write mostly Go, Javascript, and C++; with many Python one-liners & some Java in the past.
```suggestion
These days I write mostly Go, Javascript, and C++; with many Python one-liners & a bit of Java in the past.
```

2020-07-22 00:01 UTC, exterkamp requested changes
This is illegal slander.

2020-07-22 00:01 UTC, exterkamp commented on README.md
> +These days I write mostly Go, Javascript, and C++; with many Python one-liners & a bit of Java in the past. I spend my free time playing Kane & Lynch 2.
```suggestion
These days I write mostly Go, Javascript, and C++; with many Python one-liners & a bit of Java in the past.
```

2020-08-10 19:25 UTC, zdiemer commented
bump @exterkamp

2020-08-10 20:44 UTC, exterkamp commented
-1

2020-09-28 17:31 UTC, closed without merging